### ISSUE TITLE
豚骨BOYじゃなくてつけ麺BOYと名乗るべきじゃないか？

### ISSUE THREAD

**Issue by tonkotsuboy** [tonkotsuboy/suda#3]
# 概要
若かりし頃は週5〜7のペースで豚骨ラーメンを食べていたが、
最近では週1〜2に減った上に豚骨ラーメンではなくつけ麺。

とんこつBOYと名乗るのは不適切ではないか？と先輩から指摘を受けている。

# 解決案
- 豚骨ラーメンの頻度を上げる
- つけ麺BOYに改名
- 豚骨系つけ麺だから！と言い張る
- 無視する

**Comment by tonkotsuboy** [comment]
> 豚骨系つけ麺だから！と言い張る

魚介じゃないの？

**Comment by tonkotsuboy** [comment]
> 豚骨系つけ麺だから！と言い張る

濃厚魚介だろって突っ込まれたらどうしよう

**Comment by yuukiit** [comment]
> 濃厚魚介だろって突っ込まれたらどうしよう

豚骨の心をお忘れにならない限り、鹿野先生は永遠に豚骨BOYだと思います！

**Comment by tonkotsuboy** [comment]
永遠に豚骨BOYということで解決しました！！！
