### ISSUE TITLE
スダころがしの画像サイズ

### ISSUE THREAD

**Issue by tonkotsuboy** [tonkotsuboy/suda#5]
@incolorsnet 

スダころがしの画像サイズが大きく、スマートフォン閲覧時に読み込み時間がかかっている印象です。

- suda.png : 193KB
- suda2.png : 1MB

各々、JPGにして画質を落とせば、ある程度ファイルサイズを小さくできるかと思いますが、いかがでしょう？

**Comment by yuukiit** [comment]
@tonkotsuboy 

ありがとうございます！
確かにPNGのままだと画像が重く、コンソールでも警告が出ていたので
画像サイズを調整し、PNG→JPGに変更、サイズの軽量化を行いました。
PRをお送りしましたので、再度ご確認をお願いします！
